---
- name: Rolling restart + HTTPS health check (IP-based)
  hosts: masters
  become: yes
  serial: 1

  tasks:
    - name: Restart Elasticsearch
      systemd:
        name: elasticsearch
        state: restarted
        daemon_reload: yes

    - name: Wait for Elasticsearch HTTPS API
      uri:
        url: "https://{{ ansible_host }}:9200"
        validate_certs: no
        status_code: 200
      register: es_result
      retries: 30
      delay: 20
      until: es_result.status == 200
