---
- name: Configure Elasticsearch Keystore
  hosts: all
  become: yes

  vars:
    es_bin: /usr/share/elasticsearch/bin/elasticsearch-keystore

  tasks:
    - name: Create keystore if not exists
      command: "{{ es_bin }} create"
      args:
        creates: /etc/elasticsearch/elasticsearch.keystore
      become_user: elasticsearch

    - name: Set keystore permissions
      file:
        path: /etc/elasticsearch/elasticsearch.keystore
        owner: elasticsearch
        group: elasticsearch
        mode: 0600
