---
- name: Start Elasticsearch service on all nodes
  hosts: all   # Change to [masters], [data], or your specific group if needed
  become: yes

  tasks:
    - name: Start Elasticsearch service
      systemd:
        name: elasticsearch
        state: started
        daemon_reload: yes
