---
- name: Enable Elasticsearch HTTPS & X-Pack Security
  hosts: all
  become: yes

  vars:
    es_conf_dir: /etc/elasticsearch
    es_cert_dir: /etc/elasticsearch/certs
    es_user: elasticsearch
    es_group: elasticsearch

  tasks:
    - name: Create cert directory
      file:
        path: "{{ es_cert_dir }}"
        state: directory
        owner: "{{ es_user }}"
        group: "{{ es_group }}"
        mode: 0750

    - name: Copy node certificate
      copy:
        src: /home/elastic/elastic-cloudinit-/elastic_https_setup/files/certs/node.p12
        dest: "{{ es_cert_dir }}/node.p12"
        owner: "{{ es_user }}"
        group: "{{ es_group }}"
        mode: 0640

    - name: Copy CA certificate
      copy:
        src: /home/elastic/elastic-cloudinit-/elastic_https_setup/files/certs/ca.crt
        dest: "{{ es_cert_dir }}/ca.crt"
        owner: "{{ es_user }}"
        group: "{{ es_group }}"
        mode: 0644

    - name: Configure elasticsearch.yml for HTTPS
      blockinfile:
        path: "{{ es_conf_dir }}/elasticsearch.yml"
        marker: "# {mark} ANSIBLE XPACK HTTPS"
        block: |
          xpack.security.enabled: true

          xpack.security.transport.ssl.enabled: true
          xpack.security.transport.ssl.verification_mode: certificate
          xpack.security.transport.ssl.keystore.path: certs/node.p12
          xpack.security.transport.ssl.truststore.path: certs/node.p12

          xpack.security.http.ssl.enabled: true
          xpack.security.http.ssl.keystore.path: certs/node.p12
          xpack.security.http.ssl.truststore.path: certs/node.p12

    - name: Ensure ownership of Elasticsearch config
      file:
        path: "{{ es_conf_dir }}"
        owner: "{{ es_user }}"
        group: "{{ es_group }}"
        recurse: yes
