---
- name: Stop Elasticsearch service on all nodes
  hosts: all   # You can change this to [masters], [data], or your specific group
  become: yes

  tasks:
    - name: Stop Elasticsearch service
      systemd:
        name: elasticsearch
        state: stopped
        daemon_reload: yes
