---
- name: FINAL Elasticsearch permission fix (STOP THE BLEEDING)
  hosts: all
  become: yes

  vars:
    es_user: elasticsearch
    es_group: elasticsearch
    es_conf_dir: /etc/elasticsearch
    es_cert_dir: /etc/elasticsearch/certs

  tasks:

    # -------------------------
    # CONFIG DIRECTORIES
    # -------------------------
    - name: Fix /etc/elasticsearch directory
      file:
        path: "{{ es_conf_dir }}"
        owner: root
        group: "{{ es_group }}"
        mode: 0750

    - name: Fix jvm.options.d directory
      file:
        path: "{{ es_conf_dir }}/jvm.options.d"
        owner: root
        group: "{{ es_group }}"
        mode: 0750

    # -------------------------
    # CONFIG FILES
    # -------------------------
    - name: Fix config file permissions
      file:
        path: "{{ item }}"
        owner: root
        group: "{{ es_group }}"
        mode: 0640
      loop:
        - "{{ es_conf_dir }}/elasticsearch.yml"
        - "{{ es_conf_dir }}/jvm.options"
        - "{{ es_conf_dir }}/log4j2.properties"

    # -------------------------
    # KEYSTORE (CRITICAL)
    # -------------------------
    - name: Fix elasticsearch keystore
      file:
        path: "{{ es_conf_dir }}/elasticsearch.keystore"
        owner: "{{ es_user }}"
        group: "{{ es_group }}"
        mode: 0600

    # -------------------------
    # CERTS
    # -------------------------
    - name: Fix cert directory
      file:
        path: "{{ es_cert_dir }}"
        owner: "{{ es_user }}"
        group: "{{ es_group }}"
        mode: 0750

    - name: Fix cert and key files
      file:
        path: "{{ item.path }}"
        owner: "{{ es_user }}"
        group: "{{ es_group }}"
        mode: "{{ item.mode }}"
      loop:
        - { path: "{{ es_cert_dir }}/udlprd.key", mode: "0600" }
        - { path: "{{ es_cert_dir }}/udlprd.crt", mode: "0644" }
        - { path: "{{ es_cert_dir }}/ca.crt", mode: "0644" }

    # -------------------------
    # SYSTEMD
    # -------------------------
    - name: Reload systemd
      command: systemctl daemon-reexec

    - name: Restart Elasticsearch
      service:
        name: elasticsearch
        state: restarted
