---
- name: FIX Elasticsearch permissions (FINAL – PRODUCTION SAFE)
  hosts: all
  become: yes

  vars:
    es_user: elasticsearch
    es_group: elasticsearch
    es_conf_dir: /etc/elasticsearch
    es_cert_dir: /etc/elasticsearch/certs

  tasks:

    # =========================
    # CONFIG DIRECTORY
    # =========================
    - name: Ensure /etc/elasticsearch ownership and mode (REQUIRED BY SYSTEMD)
      file:
        path: "{{ es_conf_dir }}"
        owner: root
        group: "{{ es_group }}"
        mode: "0750"

    # =========================
    # CONFIG FILES
    # =========================
    - name: Fix ownership and permissions for Elasticsearch config files
      file:
        path: "{{ item }}"
        owner: root
        group: "{{ es_group }}"
        mode: "0640"
      loop:
        - "{{ es_conf_dir }}/elasticsearch.yml"
        - "{{ es_conf_dir }}/jvm.options"
        - "{{ es_conf_dir }}/log4j2.properties"
      ignore_errors: true

    # =========================
    # CERT DIRECTORY
    # =========================
    - name: Ensure cert directory ownership
      file:
        path: "{{ es_cert_dir }}"
        owner: "{{ es_user }}"
        group: "{{ es_group }}"
        mode: "0750"

    # =========================
    # CERT & KEY FILES
    # =========================
    - name: Fix TLS certificate and key permissions
      file:
        path: "{{ item.path }}"
        owner: "{{ es_user }}"
        group: "{{ es_group }}"
        mode: "{{ item.mode }}"
      loop:
        - { path: "{{ es_cert_dir }}/udlprd.key", mode: "0600" }
        - { path: "{{ es_cert_dir }}/udlprd.crt", mode: "0644" }
        - { path: "{{ es_cert_dir }}/ca.pem",     mode: "0644" }
        - { path: "{{ es_cert_dir }}/ca.crt",     mode: "0644" }
      ignore_errors: true

    # =========================
    # SYSTEMD REFRESH
    # =========================
    - name: Reload systemd manager configuration
      command: systemctl daemon-reexec

    # =========================
    # RESTART ELASTICSEARCH
    # =========================
    - name: Restart Elasticsearch service
      service:
        name: elasticsearch
        state: restarted
